account:
  msg: AMK Account Default application Resfresh Bus
  build-version: 300

  mailDetails:
    hostName: default-account@amk.com
    port: 9000
    from: default-account@amk.com
    subject: Your Account Details from AMK Default Environment

  activeBranches: 
    - Phnom Penh
    - Kompong Cham
    - Battombong

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/digitalplatform}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:digitalplatform}

  cloud:
    stream:
      bindings:
        showCustomer-out-0:
          destination: customer-communication
      kafka:
        binder:
          brokers:
            broker1: localhost:9093
            broker2: localhost:9095
