account:
  msg: AMK Account prod application
  build-version: 500

  mailDetails:
    hostName: prod-account@amk.com
    port: 9000
    from: prod-account@amk.com
    subject: Your Account Details from AMK PROD Environment

  activeBranches: 
    - Phnom Penh
    - Kompong Cham
    - Battombong
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/digital_account}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:digital_account}
  cloud:
    stream:
      bindings:
        showCustomer-out-0:
          destination: customer-communication
      kafka:
        binder:
          brokers:
          - ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}
