account:
  msg: AMK Account UAT application
  build-version: 400

  mailDetails:
    hostName: uat-account@amk.com
    port: 9000
    from: uat-account@amk.com
    subject: Your Account Details from AMK UAT Environment

  activeBranches: 
    - Phnom Penh
    - Kompong Cham
    - Battombong

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://digital-uat.cevag9x0str2.ap-southeast-1.rds.amazonaws.com:3306/digital_account}
    username: ${DB_USERNAME:digapp}
    password: ${DB_PASSWORD:digapp}

  cloud:
    stream:
      bindings:
        showCustomer-out-0:
          destination: customer-communication
      kafka:
        binder:
          brokers:
          - ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:172.11.4.72:9092}