account:
  msg: AMK Account Default application
  build-version: 300

  mailDetails:
    hostName: default-account@amk.com
    port: 9000
    from: default-account@amk.com
    subject: Your Account Details from AMK Default Environment

  activeBranches: 
    - Phnom Penh
    - Kompong Cham
    - Battombong

spring:
  application:
    name: account
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
