Notification:
  msg: AMK Notification Default application
  build-version: 300

  mailDetails:
    hostName: default-Notification@amk.com
    port: 9000
    from: default-Notification@amk.com
    subject: Your Notification Details from AMK Default Environment

  activeBranches: 
    - Phnom Penh
    - Kompong Cham
    - Battombong

spring:
  # datasource:
  #   url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/digital_notification}
  #   username: ${DB_USERNAME:root}
  #   password: ${DB_PASSWORD:digital_notification}

  cloud:
    stream:
      bindings:
        showCustomer-in-0:
          destination: customer-communication
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            broker1: localhost:9093
            broker2: localhost:9095
