Notification:
  msg: AMK Notification prod application
  build-version: 500

  mailDetails:
    hostName: prod-Notification@amk.com
    port: 9000
    from: prod-Notification@amk.com
    subject: Your Notification Details from AMK PROD Environment

  activeBranches: 
    - Phnom Penh
    - Kompong Cham
    - Battombong
spring:
  # datasource:
  #   url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/digital_Notification}
  #   username: ${DB_USERNAME:root}
  #   password: ${DB_PASSWORD:digital_Notification}
  cloud:
    stream:
      bindings:
        showCustomer-in-0:
          destination: customer-communication
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
          - ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}
