Report:
  msg: AMK Report Default application
  build-version: 300

  mailDetails:
    hostName: default-Report@amk.com
    port: 9000
    from: default-Report@amk.com
    subject: Your Report Details from AMK Default Environment

  activeBranches: 
    - Phnom Penh
    - Kompong Cham
    - Battombong

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/digitalplatform}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:digitalplatform}

  # cloud:
  #   stream:
  #     bindings:
  #       showCustomer-out-0:
  #         destination: customer-communication
  #     kafka:
  #       binder:
  #         brokers:
  #         - ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}
